VictorOps: "maint end" always resolves, and 10m more of alerts
rjbs/Synergy pull request #131
Opened 2020-09-15 20:20 UTC by rjbs

2020-09-15 20:21 UTC, rjbs commented
This is not ready for merge, because the tests fail now.  I will think about them later.

2020-09-29 20:40 UTC, rjbs commented
@Davis-A I will send this to you for review when you've accepted invite. :)

2020-09-30 02:23 UTC, Davis-A commented
Other than being bitten by the VO API timestamps being all over the shop it looks good.

2020-09-30 02:53 UTC, Davis-A requested changes
Other than being bitten by the VO API timestamps being all over the shop it looks good.

2020-09-30 02:53 UTC, Davis-A commented on lib/Synergy/Reactor/VictorOps.pm
> +        since => $timestamp - 600,
`startedAt` timestamp is in Unixtime * 1000 for millisecond resolution hence this is only winding our resolution time back by 0.6 seconds instead of 600.

VO API is poorly documented and inconsistent.  As if you look in _resolve_incidents you'll discover that for an incident the `startTime` (why the heck is it name differently too) is Unixtime....

2020-10-29 21:23 UTC, Davis-A approved these changes

2020-10-30 01:28 UTC, Davis-A commented
So the tests only failed after my commit on top to fix the 10 minute window Rik wants.  
This led me to discover there was a bug in the test.  It was setting the maint `startedAt` field to 86400.  `startedAt` is milliseconds since the unix epoch so that was setting at 86.4 seconds past epoch.

So a fixed that, then reworked the demaint /resolve test to include an additional incident before `startedAt`  but within the 10 minute window and adjusted one of the existing incidents to be closer to `startedAt` but outside of the 10 minute window

2020-10-30 13:35 UTC, merged