vo: maint timer periodically notifies oncall we're still in maint
rjbs/Synergy pull request #132
Opened 2020-09-23 03:48 UTC by Davis-A

Sometimes operators forget to demaint.

Create a timer that fires every 30 minutes to @oncall in plumbing to remind them we're in maint.

2020-09-23 03:49 UTC, Davis-A commented on lib/Synergy/Reactor/VictorOps.pm
> +sub _long_maint_warning ($self, $timer) {
I'm not exactly sure how to direct a message to plumbing and target @oncall. 
This is the only piece of the puzzle unimplemented

2020-09-23 14:11 UTC, mmcclimon requested changes
Back to you.

2020-09-23 14:11 UTC, mmcclimon commented on lib/Synergy/Reactor/VictorOps.pm
> +sub _long_maint_warning ($self, $timer) {
So, we do this in a handfull of places. It involves configuring the address (at-oncall, which we already have) and channel (pound-plumbing, which we don't), then using that. The best place to steal from here would be the LP reactor; search for `triage_address` and `_inform_triage`.

You'll eventually want something like 
```perl
  if ($self->oncall_channel_name && $self->maint_warning_address) {
    $channel->send_message($self->maint_warning_address, $text, $alt);
  }
```

Also, this method should check, before it does anything, if we're still in maint (and if we're not, cancel the timer!). 

Also also, I dislike this method name, because it's not a noun and not a verb, and I'd probably call it `send_long_maint_warning` or something.

2020-09-24 01:43 UTC, Davis-A commented on lib/Synergy/Reactor/VictorOps.pm
> +        return $e->text =~ m{^maint\s+timer\s+stop\s*$}i },
My thought was if there is ever a time we don't want it we can turn it off and it doesn't hurt to have it.  But then I guess we can activate maint via the VictorOps webui instead.

2020-09-24 01:45 UTC, Davis-A commented on lib/Synergy/Reactor/VictorOps.pm
> +  $self->maint_warning_timer(0);
I knew this would come up in the review, this was a placeholder till someone told me a better way to handle it.  To get this far I just needed something to check an if condition against and that worked.  
Thanks for telling me about `clearer` 😄

2020-09-24 02:03 UTC, Davis-A commented on lib/Synergy/Reactor/VictorOps.pm
> +    return Future->done(0);
Okie dokie.  I've used that before in the ack all and resolve all patches.  I think I copied that from the Liquid Planner reactor, a great case of I copied the 1/20 of them that was wrong and have done it wrong myself ever since.

2020-09-24 05:02 UTC, Davis-A commented on lib/Synergy/Reactor/VictorOps.pm
> +sub _send_long_maint_warning ($self, $timer) {
Two things in this method:

**One:**
I'm not sending messages to oncall.  I was hoping to find a way to send a single message to #plumbing targeting \@oncall and i couldn't figure it out, at least without more time.  So i'm wondering what you think, whether it should just send to plumbing, or follow the triage model and ping each oncall member individually in addition to sending to #plumbing?.  

**Two:**
I hate how I implemented this.  I could think of 3 bad ways to implement so I picked one.  What i really think would be easier is do the request then the `then( sub ....)` just assign `$data` to a variable declared before the request, but that also felt icky.  So really I could only think of 3 bad ideas so I picked one, which unfortunately puts the burden on you to tell me how to do it right :(

I wanted to follow the pattern in the liquidplanner reactor which is 

````
return unless $self->triage_channel_name;
return unless my $channel = $self->hub->channel_named($self->triage_channel_name);
[...]
	  
if ($self->triage_channel_name && $self->triage_address) {
  $channel->send_message($self->triage_address, $text, $alt);
}
````

But if we're in this method then the timer exists so we need to clear it if we aren't in maint.  Meaning this check has to exist after the check of maint mode.

2020-09-30 13:30 UTC, mmcclimon requested changes
With apologies I didn't think of it sooner, I have suggested a slightly different tack which I think will be a better experience and also the implementation will be less fiddly.

2020-09-30 13:30 UTC, mmcclimon commented on lib/Synergy/Reactor/VictorOps.pm
> +sub _send_long_maint_warning ($self, $timer) {
btw: you can totally target oncall, using the syntax at https://api.slack.com/reference/surfaces/formatting#mentioning-groups. It'll be something like `<!subteam^S12345>`, where `S12345` is the id of the oncall group.

2020-09-30 13:30 UTC, mmcclimon commented on lib/Synergy/Reactor/VictorOps.pm
> +        'We are still in maint',
I'd provide more detail here. I'd want to see something like "@oncall Hey, by the way, VictorOps is in maintenance mode. (Started $n minutes ago by $who.)"  I don't know if we can actually tell who started it (probably not), but knowing how long it's been around is definitely useful.

2020-09-30 13:30 UTC, mmcclimon commented on lib/Synergy/Reactor/VictorOps.pm
> +    $self->_remove_maint_timer();
So (annoying comment to follow):

I think it would be better not to stop and start this timer all the time, but rather have a timer that runs _all_ the time, just like the one that checks for changes in oncall. If I were doing it, I'd it to tick every 10 minutes, and only have it alert if it had been more than 30 minutes since maint started (and at least 25 minutes since the last alert).

This way, we still get the warning if maint is started from not-Synergy. I thought of this because yesterday we got a bunch of alerts while Slack was down, and I have occasionally started maint from my phone. If someone does that and forgets to demaint, we _especially_ want to know, because the original maint wasn't publicly visible.

2020-10-02 15:15 UTC, mmcclimon requested changes
This looks pretty good. I have made some comments, and will make some more now:

1. This will alert us every five minutes (the timer fires every 600s, and warns us if maint duration is more than 30 minutes). I think that's probably overkill. Having the timer run every 5 minutes is fine, but I would save the last-warning time into state and check that at the top of the timer tick routine.

2. The state (who started maint, and I suggest also the last time we notified about maint) will not survive a restart, and it should. That's as simple as putting that stuff into `sub state`, and making sure that `->save_state` gets called after they're set.

3. I would reconsider the current behavior of suppressing the notification if there's been an alert recently. This might turn out to be a bad idea, but I'd rather synergy be too noisy and tune-downable rather than have us miss the warnings because rblcheck or whatever happened to fire at an inopportune time.

2020-10-02 15:15 UTC, mmcclimon commented on lib/Synergy/Reactor/VictorOps.pm
> +      $is_new_incident = 1, last if $incident_duration < (60 * 25);
I'm not sure what this `$incident_duration` stuff is even doing. I think an incident is an alert, and the point of this block is that we don't send the warning if there's been an alert in the last 25 minutes?

A few things: 
a) `$is_new_incident = 1, last` reads weirdly to me, and I'd split it into different statements.
b) But that's no so important, because I'm not sure that's a great idea anyway. Say there's some alert fire, and we enter maint. That incident ends in 15 minutes, but maint was not resolved. Some time later, some unrelated thing fires. I think we still want the "hey we're in maint" warning, because that second alert might not have been noticed in the meantime (by virtue of the fact that we're in maint, which we might have forgotten)!

2020-10-02 15:16 UTC, mmcclimon commented
Oh also: I would always prefer more commits for substantial changes rather than amending the same one over and over. That gives you an opportunity to write a bit about why the changes are necessary, rather than having them lost to the sands of time in Github PR comments.

2020-10-05 00:21 UTC, Davis-A commented on lib/Synergy/Reactor/VictorOps.pm
> +      $is_new_incident = 1, last if $incident_duration < (60 * 25);
a) i've seen that pattern in a dozen of our cli tools, so i thought it was acceptable.

b) Incident is VO nomenclature for an alert.  
Totally agree it is strange.  But it was based on your feedback.

>If I were doing it, I'd it to tick every 10 minutes, and only have it alert if it had been more than 30 minutes since maint started (and at least 25 minutes since the last alert).

Something lost in translation I guess.  How was I supposed to interpret the latter part in the ( ) ?

2020-10-05 12:54 UTC, mmcclimon commented on lib/Synergy/Reactor/VictorOps.pm
> +      $is_new_incident = 1, last if $incident_duration < (60 * 25);
a) I only recall having seen it in `print($usage->text), exit if $opt->help`, which is an idiom by itself and basically the only place I ever use the comma operator.

b) Aha, this was totally clear to me and I did not express it well even a little. I meant: if it had been more than 30 minutes since maint started (and at least 25 minutes since the last time Synergy notified us about ongoing maint). That is: "alert" in parens was "the synergy long-maint alert," but I can see now that that is not at all clear. Sorry!

2020-10-05 12:55 UTC, mmcclimon commented on lib/Synergy/Reactor/VictorOps.pm
> +      $is_new_incident = 1, last if $incident_duration < (60 * 25);
Which is to say: I think we should get this long-maint warning every 30m or so while we're in maint, but that involves a bit of housekeeping to make sure you don't send it on every tick.

2020-10-23 01:10 UTC, Davis-A commented
I think i've got everything!

2020-10-27 13:42 UTC, merged

2020-10-27 13:45 UTC, mmcclimon commented
@Davis-A Thanks! I have added two fiddly commits on top of this and merged.